export const FETCH_USERS_LOADING = "FETCH_USERS_LOADING";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_RESTAURANTS_LOADING = "FETCH_RESTAURANTS_LOADING";
export const FETCH_RESTAURANTS_FAILED = "FETCH_RESTAURANTS_FAILED";
export const FETCH_RESTAURANTS_SUCCESS = "FETCH_RESTAURANTS_SUCCESS";